### PR TITLE
Create an external service with Eliom dev.

### PR DESCRIPTION
**Pull request by dannywillems**

### CODE REVIEW

**Comment by Drup** [comment]
You need to add an entry to `menu.wiki`.

I would suggest changing the name: consider the doesn't know what an external link is, she would not look at this. Maybe "How to link to external websites" ?

**Comment by vasilisp** [comment]
Wouldn't it be better to improve `how-to-do-links-to-other-pages` as appropriate? The overlap worries me. We have a lot of redundant documentation already, and it is a real maintenance burden.

**Comment by Drup** [comment]
Oh, I didn't noticed that one, I definitely agree with @vasilisp.

**Comment by dannywillems** [comment]
@vasilisp @Drup First, I made changes in this page but It's two different things. We can use Eliom_client.change_page to change the page to an external service and it's not a link. For this reason, I chose to write a different page.

I think the term «external services» is explained in the tutorial.

**Comment by Drup** [comment]
I would still merge the two. We have a lot of howto, and they have too much overlaps. Having an how to "Everything you ever wanted to know about links" sounds right.

**Comment by dannywillems** [comment]
It can be interesting to have a lot of howto because when we are looking for something, we don't want to have a lot of information. For example, if we want to know "How to create external services", we don't want to know how to create links and viceverca.

It's not a good way to have everything in the same place because there are too information and when we search for something, we want something very precise, not something large.

**Comment by dannywillems** [comment]
Do I have to do something else?
Do I merge the two pages in one?

**Comment by vasilisp** [comment]
Yes, I would appreciate it if you merged them.

External services are used for links 90% of the time. When used in more complicated ways like arbitrary Eliom services, we are talking about an advanced user who can read the API doc of `Eliom_service` and doesn't need a mini-HOWTO. So explaining external services only in the context of links is sufficient.

**Comment by dannywillems** [comment]
See #43

**Pull request closed without merging**
