### PR TITLE
Precision about opened module.

### PR DESCRIPTION
**Pull request by dannywillems**
When we go in the documentation of Eliom_form_sigs.LINKS (http://ocsigen.org/eliom/dev/api/client/Eliom_form_sigs.LINKS, I supposed make_uri comes from this signature which is included in Eliom_content.Html.D), the make_uri signature has a labeled argument for the service, but we don't need to use this label, why?

### CODE REVIEW

**Comment by Drup** [comment]
As @vasilisp suggested in another PR, please use linkified module names.

As for not using the label, it may work, but it's kind of fishy ...

**Comment by dannywillems** [comment]
@Drup

> use linkified module names

 What do you mean?

**Comment by dannywillems** [comment]
@Drup I create it with {{{ }}} or with <<a_api project="..." subproject="..." | val f >>?
There is no documentation about the syntax.

**Comment by Drup** [comment]
If you look a bit below, you can see this:
```
<<a_api project="eliom" subproject="server"|val Eliom_tools.F.head>>
```

That's the good syntax, be careful to change the project/subproject target when appropriate.

**Pull request merged**
