### PR TITLE
Remove eliom-distillery

### PR DESCRIPTION
**Pull request by dannywillems**
It seems outdated and it's old services API.

What about `chat` and `chat3` directories?

### CODE REVIEW

**Comment by vasilisp** [comment]
All three directories contain old stuff that nobody has bothered to remove or update. We can remove them if you want, just so that nobody thinks they are a good starting point for learning Ocsigen.

**Comment by vasilisp** [comment]
Some of the stuff under `files` might be worth rescuing, however.

**Comment by dannywillems** [comment]
@vasilisp I also removed chat and chat3.
I think `eliom-distillery` directory contains the old Ocsigen Start idea. It would be interesting to write a chat with Ocsigen Start and replace these examples.

**Comment by vasilisp** [comment]
> It would be interesting to write a chat with Ocsigen Start and replace these examples.

Sure. We have quite a few chat implementations in different places, we might as well publish a working one.

**Pull request merged**
