### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by dannywillems**
See mailing list.

### CODE REVIEW

**Comment by vasilisp** [comment]
While we are at it, `Official W3` -> `W3Schools`? `W3Schools` is a useful resource, but there is nothing official about it.

**Comment by dannywillems** [comment]
@vasilisp I agree with you. I change. I hesitated to remove official.

**Comment by dannywillems** [comment]
@vasilisp Changed.

**Comment by vasilisp** [comment]
Thanks!

**Pull request merged**
