### PR TITLE
Precision about opened module.

### PR DESCRIPTION
**Pull request by dannywillems**
And this link redirects to the 5.0 version, which is not we want because Html5 doesn't exist.

```
<<a_api project="eliom" subproject="server" |val Eliom_content.Html5.D.make_uri>>
```

### CODE REVIEW

**Comment by Drup** [comment]
Could you also change the wrong link please ? :)

**Comment by dannywillems** [comment]
I don't know how to redirect to the dev version. It redirects to the the 5.0 version.

**Comment by Drup** [comment]
I'm pretty sure fixing the module name (`HTML5` -> `HTML` will be enough).

**Comment by dannywillems** [comment]
Fixed.

**Pull request merged**
